### ISSUE TITLE
[오탈자 신고] <네이밍 -변수>

### ISSUE THREAD

**Issue by taek0622** [DeveloperAcademy-POSTECH/swift-style-guide#15]
### 이슈 중복 확인

- [x] 검색을 통해 중복되지 않은 이슈임을 확인

### 카테고리

네이밍 - 변수

### 내용

네이밍 - 변수의 첫째 줄, "변수 이름은 `lowerCammerCase`를 사용해주세요."에서 `lowerCamelCase`가 `lowerCammerCase`로 오타가 난 것 같습니다.

**Comment by JUNY0110** [comment]
assignee 드렸습니다~
