### ISSUE TITLE
[내용 추가] <네이밍 - 함수>

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/swift-style-guide#17]
### 이슈 중복 확인

- [x] 검색을 통해 중복되지 않은 이슈임을 확인

### 카테고리

Naming of Functions

**Comment by M1zz** [comment]
중복되지 않은 이슈에 체크 해주세요!

**Comment by M1zz** [comment]
PR을 기다리겠습니다!
