### ISSUE TITLE
[내용 추가] <띄어쓰기>

### ISSUE THREAD

**Issue by LeeSungNo-ian** [DeveloperAcademy-POSTECH/swift-style-guide#25]
### 이슈 중복 확인

확인했습니다!

### 카테고리

클론 `:` 을 사용할 때, 오른쪽 공백 한 칸이 필요할 것 같습니다.

**Comment by M1zz** [comment]
할당했습니다 PR부탁드립니다!

**Comment by M1zz** [comment]
@LeeSungNo-ian 하다가 어려운 부분이 있으면 여기에 코멘트 남겨주세요!

**Comment by LeeSungNo-ian** [comment]
커밋에 대한 실수를 했습니다..
수정 후 작업하겠습니다 죄송합니다.

**Comment by LeeSungNo-ian** [comment]
@M1zz 

들여쓰기는 [여기](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide/pull/33)에 포함이 되는 것 같은데 추가 작업이 필요할까요?!

**Comment by M1zz** [comment]
@LeeSungNo-ian 이 이슈는 들여쓰기 중 콜론에 관한 내용추가가 필요하다는 것을 제안하는 이슈이고

새로운 이슈인 띄어쓰기라는 이름을 들여쓰기로 바꾸자 라는 이슈를 하나 만들어 달라는 요청이었습니다 ㅎ ㅎ

**Comment by LeeSungNo-ian** [comment]
@M1zz 

아! 이해했습니다! 새롭게 이슈 만들겠습니다 ㅎㅎ
