### ISSUE TITLE
[내용 추가] <타입>

### ISSUE THREAD

**Issue by imparang** [DeveloperAcademy-POSTECH/swift-style-guide#29]
### 이슈 중복 확인

확인했습니다.

### 카테고리

데이터 타입에 따른 Type Inference와 Type annotation 작성

**Comment by taek0622** [comment]
타입에 관한 어떤 내용인지 명확하지 않습니다.
카테고리를 타입 중에서 어떤 내용인지 조금만 더 명확히 써주시면 좋을 것 같아요.

**Comment by imparang** [comment]
> 타입에 관한 어떤 내용인지 명확하지 않습니다.
> 카테고리를 타입 중에서 어떤 내용인지 조금만 더 명확히 써주시면 좋을 것 같아요.

수정했습니다!

**Comment by taek0622** [comment]
확인했습니다. 어싸인 드렸습니다~😃
