### ISSUE TITLE
[내용 추가] <클래스 스트럭트 네이밍>

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/swift-style-guide#35]
### 이슈 중복 확인

확인했습니다

### 카테고리

Class, Struct, Enum, 파일 명 네이밍 컨벤션 (Camel Case)

**Comment by M1zz** [comment]
작업 부탁드려도 될까요? ㅎ ㅎ 어사인 했습니다!

**Comment by M1zz** [comment]
@yeniful 작업하다가 여러운 부분이 있으시면 알려주세요! ㅎ ㅎ
