### ISSUE TITLE
[내용 수정 및 삭제] <Add 띄어쓰기 #33 -> 들여쓰기로 수정>

### ISSUE THREAD

**Issue by LeeSungNo-ian** [DeveloperAcademy-POSTECH/swift-style-guide#39]
### 이슈 중복 확인

확인했습니다!

### 카테고리

들여쓰기

### 수정 이유

[Add 띄어쓰기 #33](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide/pull/33)의 제목을 `들여쓰기`로 수정해야 될 것 같아 이슈를 남깁니다!

**Comment by M1zz** [comment]
제안 감사드려요! 부탁드릴게요 이안

**Comment by LeeSungNo-ian** [comment]
기존 PR이 머지가 된 후 작업하겠습니다! 😀

**Comment by M1zz** [comment]
@LeeSungNo-ian 작업 부탁드립니다!
