### ISSUE TITLE
[내용 수정 및 삭제] <함수명 fetch, request에 대한 의문점>

### ISSUE THREAD

**Issue by insub4067** [DeveloperAcademy-POSTECH/swift-style-guide#44]
### 이슈 중복 확인

확인했습니다.

### 카테고리

함수

### 수정 이유

본문 내용
👇👇👇👇
데이터를 가져오는 함수의 경우, get 사용을 지양하고 request, fetch을 적절하게 사용해주세요.
request : 에러가 발생하거나, 실패할 수 있는 비동기 작업에 사용합니다.
fetch : 요청이 실패하지 않고 결과를 바로 반환할 때 사용합니다.

요청이 실패하지 않는 경우에 대한 기준이 모호하게 느껴집니다.
어느 경우에 라도 요청이 실패할수 있는 경우는 존재한다고 생각이 듭니다.
기준이 있다면 보다 명확한 기준의 예시를 들어주는 것도 필요해 보입니다.

**Comment by insub4067** [comment]
request는 http 통신을 하는 경우/ fetch는 그외 data를 가지고 오는 행위를 총칭하면 어떨까요?

**Comment by M1zz** [comment]
수정 제안 부탁드립니다

**Comment by insub4067** [comment]
request : http 통신을 통해 값을 요청하는 경우 사용합니다.
fetch : 그외 data를 찾고자 하는 모든 행위에 대해 사용합니다.

라고 정리하면 될까요?

**Comment by insub4067** [comment]
PR 요청 하였습니다
