### ISSUE TITLE
[내용 추가] <네이밍 - 함수>

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/swift-style-guide#5]
### 이슈 중복 확인

- [ ] 검색을 통해 중복되지 않은 이슈임을 확인

### 카테고리

없음

### 프레임워크 이름

없음

### 프레임워크 공식문서 URL

없음

### 풀리퀘스트 여부

- [ ] 풀리퀘스트 완료

**Comment by M1zz** [comment]
이슈 템플릿이 바뀌었습니다 다시 생성 부탁드릴게요 죄송합니다 ㅠ

**Comment by Lia316** [comment]
기존 이슈 템플릿이 저희 레포의 맥락과 맞지 않아 수정했습니다!
@Apple-Kong 수정된 템플릿에 맞게 새로 이슈 등록해주실 수 있을까요?

PR 등록 후에는 해당 PR에 이슈 연동하시면 됩니다!
자세한 사항은 [컨트리뷰션 가이드라인](https://github.com/DeveloperAcademy-POSTECH/swift-style-guide/blob/main/.github/CONTRIBUTING.md)를 참고해주세요

**Comment by Apple-Kong** [comment]
확인해서 다시 이슈 등록 완료헀습니다!
