### ISSUE TITLE
[내용 수정 및 삭제] <세부정보>

### ISSUE THREAD

**Issue by yeniful** [DeveloperAcademy-POSTECH/swift-style-guide#50]
### 이슈 중복 확인

확인했습니다

### 카테고리

Template

### 수정 이유

스타일 가이드에 내용이 많이 추가되면 문서 길이가 길어질 것 같은데
자세한 설명이나 코드들은 토글로 접어두는건 어떨까 제안해봅니다!
에어비앤비 스타일 가이드를 참고했어요
https://github.com/airbnb/swift

**Comment by M1zz** [comment]
등장할 타이밍 이라고 생각하고 있었습니다

**Comment by M1zz** [comment]
작업이 오랫동안 이루어지지 않아서 제가 진행하도록 하겠습니다!
