### ISSUE TITLE
[내용 수정 및 삭제] <함수 네이밍 컨벤션 들여쓰기 수정>

### ISSUE THREAD

**Issue by Apple-Kong** [DeveloperAcademy-POSTECH/swift-style-guide#58]
### 이슈 중복 확인

확인했습니다

### 카테고리

Naming of Functions

### 수정 이유

새로 추가된 들여쓰기 컨벤션과 함수 네이밍 컨벤션 파트의 예제 코드의 들여쓰기가 일치하지 않아 수정하고자 합니다

**Comment by M1zz** [comment]
네 부탁드립니다!
